---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/lumyriam/coravi.lumyriam.com/
    - export REPOPATH=/home3/lumyriam/repositories/repairShop
    - /bin/rsync -a --exclude '.git' $REPOPATH $DEPLOYPATH